name: Webapp CI/CD pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    name: Build Backend
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
      - name: Build Backend application
        if: steps.filter.outputs.backend == 'true'
        run: |
          echo "Building backend application..."
      - name: Build docker image
        run: docker build -t aleksandrscikinovs/webapp-backend ./backend  
      - name: Push docker image
        run: docker push aleksandrscikinovs/webapp-backend

  build-frontend:
    name: Build Frontend
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'frontend/**'
      - name: Build Frontend application
        if: steps.filter.outputs.frontend == 'true'
        run: |
          echo "Building frontend application..."
      - name: Build docker image
        run: docker build -t aleksandrscikinovs/webapp-frontend ./frontend  
      - name: Push docker image
        run: docker push aleksandrscikinovs/webapp-frontend

  deploy-backend-dev:
    name: Deploy Backend to Kubernetes DEV
    runs-on: self-hosted
    needs: [build-backend]
    steps:
      - run: echo "Deploying Backend to DEV..."

  deploy-frontend-dev:
    name: Deploy Frontend to Kubernetes DEV
    runs-on: self-hosted
    needs: [build-frontend]
    steps:
      - run: echo "Deploying Frontend to DEV..."

  test-backend-dev:
    name: Run API Tests against DEV Backend
    runs-on: self-hosted
    needs: [deploy-backend-dev]
    steps:
      - run: echo "Running tests on DEV..."

  deploy-backend-stg:
    name: Deploy Backend to Kubernetes STG
    runs-on: self-hosted
    needs: [test-backend-dev]
    steps:
      - run: echo "Deploying Backend to STG..."

  deploy-frontend-stg:
    name: Deploy Frontend to Kubernetes STG
    runs-on: self-hosted
    needs: [deploy-frontend-dev]
    steps:
      - run: echo "Deploying Frontend to STG..."

  test-backend-stg:
    name: Run API Tests against STG Backend
    runs-on: self-hosted
    needs: [deploy-backend-stg]
    steps:
      - run: echo "Running tests on STG..."

  deploy-backend-prd:
    name: Deploy Backend to Kubernetes PRD
    runs-on: self-hosted
    needs: [test-backend-stg]
    steps:
      - run: echo "Deploying Backend to PRD..."

  deploy-frontend-prd:
    name: Deploy Frontend to Kubernetes PRD
    runs-on: self-hosted
    needs: [deploy-frontend-stg]
    steps:
      - run: echo "Deploying Frontend to PRD..."

  test-backend-prd:
    name: Run API Tests against PRD Backend
    runs-on: self-hosted
    needs: [deploy-backend-prd]
    steps:
      - run: echo "Running tests on PRD..."
